### ISSUE TITLE
how to call     qc = QuickFirefox(work=0,args='')     qc.create_a_driver()

### ISSUE THREAD

**Issue by wanghaisheng** [kuro7766/BilibiliUp#2]
I cannot figure out how to call create_a_driver in  0_bilibili_playcount_up.py

**Comment by kuro7766** [comment]
You shouldn't use `QuickFirefox` directly . Use `quick_firefox.run_sync` instead
Here is a minimize example:
```
import quick_firefox
from selenium.webdriver.firefox.webdriver import WebDriver
def callback(_driver: WebDriver, arguments):
  # use this _driver object to do anything you want
  return 1 
if __name__=='__main__':
    result=quick_firefox.run_sync(work=callback, args=())  # args will be callback function's parameters
```
This code is able to run directly with proper firefox and geckodriver environment.

`quick_firefox.run_sync` will do these things:
- prepare environment for firefox and run a firefox instance
- pass _driver object to user callback  function
- after user callback function is finished , it will automatically clean and kill running processes. Then destroy WebDriver instance
- if timeout is reached , it will automatically kill driver process too. Default timeout for `run_sync` function is 300s. You can change it by `quick_firefox.run_sync(work=callback, args=(),timeout=500)`

So what you need to do is review selenium WebDriver Api and program in the callback function using _driver object.

And if you want to use python package in callback function scope , you have to import it again separately even if you have already import it in outter scope.Because callback function will run in a different process and python modules are not shared.
Use `import time` example:
- correct
```
import quick_firefox
import time
from selenium.webdriver.firefox.webdriver import WebDriver
def callback(_driver: WebDriver, arguments):
  # use this _driver object to do anything you want
  import time
  print(time.time())
  return 1 
if __name__=="__main__":
    result=quick_firefox.run_sync(work=callback, args=())  # args will be callback function's parameters
```

- error , because time module is not import in callback scope , it's in another process
```
import quick_firefox
import time
from selenium.webdriver.firefox.webdriver import WebDriver
def callback(_driver: WebDriver, arguments):
  # use this _driver object to do anything you want
  print(time.time())
  return 1 
if __name__=="__main__":
    result=quick_firefox.run_sync(work=callback, args=())  # args will be callback function's parameters
```

**Comment by wanghaisheng** [comment]
inside quick_firefox,define a :
```
def init_web_driver(_driver: webdriver):
    return _driver
```
call in other function as 
```
    web_driver = quick_firefox.run_sync(work=init_web_driver,args='')

```
forgive i am a code dummy,i only want a instance of webdriver to do something

**Comment by kuro7766** [comment]
You want to get driver instance outside callback function anyway?

I think a callback fun with driver and arguments can do everything.

**Comment by wanghaisheng** [comment]
i have other function can scrape youtube channel latest videos and i need a webdriver instance for it.
locally i use selenium chrome and since there is quickfirefox  i thought  expose an instance is quite simple but got stuck with taht
then i can connect your code and mine to a new one

**Comment by kuro7766** [comment]
I'm afraid they can't work well together . It's designed that you have to use _driver in callback scope . You can try migrating your getvideourl into this function . Because use driver outside will cause nullptr problem easily.

**Comment by wanghaisheng** [comment]
you mean like this ?


def getvideourl (_driver: webdriver):
balabala
    return videolist

**Comment by kuro7766** [comment]
Yes . Then pass videolist to another `run_sync` as it's arguments.

**Comment by wanghaisheng** [comment]
i do need your help .this method return result is a int type when check action run log

https://github.com/wanghaisheng/YoutubeViewBoostBot/blob/main/0_youtube_playcount_up.py

**Comment by kuro7766** [comment]
There is a big problem in your code . You can open an issue in your repository . I will explain it to you .

**Comment by wanghaisheng** [comment]
for forked repo ,there is none issue and discussion panel . jiong

**Comment by kuro7766** [comment]
You can open it by settings -> options -> issue
